param demo_name string = 'gh-demo-20251110'
param registry_name string = 'ghdemo20251110'
param github_repo string = 'rla-${demo_name}/demo'


param containerapps_backend_name string = 'backend'
param containerapps_frontend_name string = 'frontend'
param userAssignedIdentities_gh_actions_name string = 'gh-actions'

resource managedEnvironments_resource 'Microsoft.App/managedEnvironments@2025-02-02-preview' = {
  name: demo_name
  location: 'France Central'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    appLogsConfiguration: {}
    zoneRedundant: false
    kedaConfiguration: {}
    daprConfiguration: {}
    customDomainConfiguration: {}
    workloadProfiles: [
      {
        workloadProfileType: 'Consumption'
        name: 'Consumption'
        enableFips: false
      }
    ]
    peerAuthentication: {
      mtls: {
        enabled: false
      }
    }
    peerTrafficConfiguration: {
      encryption: {
        enabled: false
      }
    }
    publicNetworkAccess: 'Enabled'
  }
}

resource registry_resource 'Microsoft.ContainerRegistry/registries@2025-05-01-preview' = {
  name: registry_name
  location: 'francecentral'
  sku: {
    name: 'Basic'
    tier: 'Basic'
  }
  properties: {
    adminUserEnabled: false
    policies: {
      quarantinePolicy: {
        status: 'disabled'
      }
      trustPolicy: {
        type: 'Notary'
        status: 'disabled'
      }
      retentionPolicy: {
        days: 7
        status: 'disabled'
      }
      exportPolicy: {
        status: 'enabled'
      }
      azureADAuthenticationAsArmPolicy: {
        status: 'enabled'
      }
      softDeletePolicy: {
        retentionDays: 7
        status: 'disabled'
      }
    }
    encryption: {
      status: 'disabled'
    }
    dataEndpointEnabled: false
    publicNetworkAccess: 'Enabled'
    networkRuleBypassOptions: 'AzureServices'
    networkRuleBypassAllowedForTasks: false
    zoneRedundancy: 'Disabled'
    anonymousPullEnabled: false
    metadataSearch: 'Disabled'
    roleAssignmentMode: 'LegacyRegistryPermissions'
    autoGeneratedDomainNameLabelScope: 'Unsecure'
  }
}

resource userAssignedIdentities_gh_actions_resource 'Microsoft.ManagedIdentity/userAssignedIdentities@2025-01-31-preview' = {
  name: userAssignedIdentities_gh_actions_name
  location: 'francecentral'
}

resource containerapps_backend_resource 'Microsoft.App/containerapps@2025-02-02-preview' = {
  name: containerapps_backend_name
  location: 'France Central'
  kind: 'containerapps'
  identity: {
    type: 'None'
  }
  properties: {
    managedEnvironmentId: managedEnvironments_resource.id
    environmentId: managedEnvironments_resource.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: false
        targetPort: 8080
        exposedPort: 0
        transport: 'Auto'
        traffic: [
          {
            weight: 100
            latestRevision: true
          }
        ]
        allowInsecure: false
        clientCertificateMode: 'Ignore'
        stickySessions: {
          affinity: 'none'
        }
      }
      registries: [
        {
          server: '${registry_name}.azurecr.io'
          identity: 'system-environment'
        }
      ]
      identitySettings: []
      maxInactiveRevisions: 100
    }
    template: {
      containers: [
        {
          image: '${registry_name}.azurecr.io/${containerapps_backend_name}:latest'
          imageType: 'ContainerImage'
          name: containerapps_backend_name
          env: [
            {
              name: 'ASPNETCORE_ENVIRONMENT'
              value: 'Development'
            }
          ]
          resources: {
            cpu: json('0.25')
            memory: '0.5Gi'
          }
          probes: []
        }
      ]
      scale: {
        minReplicas: 0
        maxReplicas: 10
        cooldownPeriod: 300
        pollingInterval: 30
      }
      volumes: []
    }
  }
}

resource containerapps_frontend_resource 'Microsoft.App/containerapps@2025-02-02-preview' = {
  name: containerapps_frontend_name
  location: 'France Central'
  kind: 'containerapps'
  identity: {
    type: 'None'
  }
  properties: {
    managedEnvironmentId: managedEnvironments_resource.id
    environmentId: managedEnvironments_resource.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 8080
        exposedPort: 0
        transport: 'Auto'
        traffic: [
          {
            weight: 100
            latestRevision: true
          }
        ]
        allowInsecure: false
        clientCertificateMode: 'Ignore'
        stickySessions: {
          affinity: 'none'
        }
      }
      registries: [
        {
          server: '${registry_name}.azurecr.io'
          identity: 'system-environment'
        }
      ]
      identitySettings: []
      maxInactiveRevisions: 100
    }
    template: {
      containers: [
        {
          image: '${registry_name}.azurecr.io/${containerapps_frontend_name}:latest'
          imageType: 'ContainerImage'
          name: 'frontent'
          env: [
            {
              name: 'WEATHER_URL'
              value: 'https:/${containerapps_backend_name_resource.properties.configuration.ingress.fqdn}'
            }
          ]
          resources: {
            cpu: json('0.25')
            memory: '0.5Gi'
          }
          probes: []
        }
      ]
      scale: {
        minReplicas: 0
        maxReplicas: 10
        cooldownPeriod: 300
        pollingInterval: 30
      }
      volumes: []
    }
  }
}

resource userAssignedIdentities_gh_actions_branch_deploy 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2025-01-31-preview' = {
  parent: userAssignedIdentities_gh_actions_resource
  name: 'branch-deploy'
  properties: {
    issuer: 'https://token.actions.githubusercontent.com'
    subject: 'repo:${github_repo}/demo:ref:refs/heads/deploy'
    audiences: [
      'api://AzureADTokenExchange'
    ]
  }
}

resource userAssignedIdentities_gh_actions_branch_main 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2025-01-31-preview' = {
  parent: userAssignedIdentities_gh_actions_resource
  name: 'branch-main'
  properties: {
    issuer: 'https://token.actions.githubusercontent.com'
    subject: 'repo:${github_repo}/demo:ref:refs/heads/main'
    audiences: [
      'api://AzureADTokenExchange'
    ]
  }
}
